version: '3.3'
services:
  app:
    image: randyblancett/2009scape:java-11-latest
    # image: local/2009scape:java-11-latest
    container_name: "2009scape_app"
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "43595:43595"

  database:
    image: mysql:8.4.0
    container_name: "2009scape_db"
    restart: always
    ports:
      - "3306:3306" 
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "database"]
            timeout: 20s
            retries: 10
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ROOT_USER: "root"