---
name: Build Configurations and Push them to sub projects.
run-name: Building Docker Image
on:
  push:
  repository_dispatch:
    types: [template-update]

jobs:
  Build-Java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 16]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up multi JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "adopt"
          cache: maven

      - name: Pull submodules
        working-directory: ./server
        run: |
          ./build -qgcg

      # - run: mkdir -p ./server/builddir/
      # - run: echo "hello" > ./server/builddir/server.jar

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-${{ matrix.java-version }}.jar
          path: ./server/builddir/server.jar

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: Dockerfile-${{ matrix.java-version }}
          path: ./Dockerfile

      - name: Upload World Properties
        uses: actions/upload-artifact@v4
        with:
          name: World_Properties-${{ matrix.java-version }}
          path: ./resources/worldprops/*

      - name: Upload Data Files
        uses: actions/upload-artifact@v4
        with:
          name: Data_Files-${{ matrix.java-version }}
          path: ./server/Server/data/*

      - name: Upload Start.sh
        uses: actions/upload-artifact@v4
        with:
          name: Start_Script-${{ matrix.java-version }}
          path: ./resources/start.sh

  Build-Docker:
    runs-on: ubuntu-latest
    needs: Build-Java
    strategy:
      matrix:
        java-version: [11]
    steps:
      - name: Download Server Artifact
        uses: actions/download-artifact@v4
        with:
          name: server-${{ matrix.java-version }}.jar
          path: .

      - name: Download DockerFile
        uses: actions/download-artifact@v4
        with:
          name: Dockerfile-${{ matrix.java-version }}
          path: .

      - name: Download World Properties
        uses: actions/download-artifact@v4
        with:
          name: World_Properties-${{ matrix.java-version }}
          path: .

      - name: Data Files Properties
        uses: actions/download-artifact@v4
        with:
          name: Data_Files-${{ matrix.java-version }}
          path: default_data/

      - name: Download Start Script
        uses: actions/download-artifact@v4
        with:
          name: Start_Script-${{ matrix.java-version }}
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: randyblancett/2009scape

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: randyblancett/2009scape:java-${{ matrix.java-version }}-latest
