---
name: Build Configurations and Push them to sub projects.
run-name: Building Docker Image
on:
  push:
  repository_dispatch:
    types: [template-update]

jobs:
  Build-Java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 16]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up multi JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "adopt"
          cache: maven

      - name: Pull submodules
        working-directory: ./server
        run: |
          ./build -qgcg

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-${{ matrix.java-version }}.jar
          path: ./server/builddir/server.jar
          retention-days: 1

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: Dockerfile-${{ matrix.java-version }}
          path: ./Dockerfile
          retention-days: 1

  Build-Docker:
    runs-on: ubuntu-latest
    needs: Build-Java
    strategy:
      matrix:
        java-version: [11]
    steps:
      - name: Download Server Artifact
        uses: actions/download-artifact@v4
        with:
          name: server-${{ matrix.java-version }}.jar
          path: ./Code
      - name: Download DockerFile
        uses: actions/download-artifact@v4
        with:
          name: Dockerfile-${{ matrix.java-version }}
          path: ./Build
      - run: ls -l
      - run: ls -l Build
      - run: mv Code/* .
      - run: mv Build/* .
      - run: ls -l
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 2009scape-java-${{ matrix.java-version }}:latest
