---
name: Build Configurations and Push them to sub projects.
run-name: Building Docker Image
on:
  push:
  repository_dispatch:
    types: [template-update]

jobs:
  Build-Java:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Pull submodules
        working-directory: ./server
        run: |
          pwd
          git status
          git config --get remote.origin.url
          echo ${GITLAB_PULL_TOKEN}
          echo ${{ secrets.GITLAB_PULL_TOKEN }}

        # with:
        #   submodules: "recursive"
        #   token: ${{ secrets.GITLAB_PULL_TOKEN }}
        #   lfs: true
