---
name: Build Configurations and Push them to sub projects.
run-name: Building Docker Image
on:
  push:
  repository_dispatch:
    types: [template-update]

jobs:
  Build-Java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 16 ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up multi JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: maven
      - name: Pull submodules
        working-directory: ./server
        run: |
          ./build -qgcg
          ls ./Server/target
          

        # with:
        #   submodules: "recursive"
        #   token: ${{ secrets.GITLAB_PULL_TOKEN }}
        #   lfs: true
